### PR TITLE
Candle builder. Some questions and proceeding forward.

### PR DESCRIPTION
**Pull request by andrewrgarcia**
I am passing a script which now treats the footprint.csv data to lump all open close times that are unique together along with their values (see commit messages). 

My questions are now tied to the next steps on proceeding forward; how to build these footprint candles graphically; are each of the bid ask volume values stacked in any specific order? are they stacked from the open -to - the close mark? how is the ohlc candle structure exactly for these footprints? 

Besides this, it would be helpful if you do some research on how to add text to ohlc candles so that the emulate the footprint structure (perhaps adding text to the graph?)

### CODE REVIEW

**Comment by QuantFreedom1022** [comment]
When i try to run the footprint.py ... anything under 500k gives me this indexing error ... not sure if you are dealing with that as well 
```
(qfFree) E:\Coding\Footprints>"E:/Coding/virtual environments/qfFree/Scripts/python.exe" e:/Coding/Footprints/footprint.py
without @njit: 6.761 seconds
Traceback (most recent call last):
  File "e:\Coding\Footprints\footprint.py", line 334, in <module>
    pd.DataFrame(handler.Convert_tick_data_volume_candles(data, user_vol_size('500-k')), columns=req_cols).dropna().to_csv('footprint_test.csv')
  File "e:\Coding\Footprints\footprint.py", line 288, in Convert_tick_data_volume_candles
    imb_candles = self.aggregate_volumes(imb_candles, grouped_by_uni_prices, uni_sides_in_group_p, side=1)
  File "e:\Coding\Footprints\footprint.py", line 197, in aggregate_volumes
    candles = self.append_to_candle(candles)
  File "e:\Coding\Footprints\footprint.py", line 140, in append_to_candle
    candles[self.num_row, int(i)] = features[i]
IndexError: index 1000000 is out of bounds for axis 0 with size 1000000
```

**Comment by andrewrgarcia** [comment]
> When i try to run the footprint.py ... anything under 500k gives me this indexing error ... not sure if you are dealing with that as well
> 
> right now i am going through the code and will get back to you as soon as i can
> 
> ```
> (qfFree) E:\Coding\Footprints>"E:/Coding/virtual environments/qfFree/Scripts/python.exe" e:/Coding/Footprints/footprint.py
> without @njit: 6.761 seconds
> Traceback (most recent call last):
>   File "e:\Coding\Footprints\footprint.py", line 334, in <module>
>     pd.DataFrame(handler.Convert_tick_data_volume_candles(data, user_vol_size('500-k')), columns=req_cols).dropna().to_csv('footprint_test.csv')
>   File "e:\Coding\Footprints\footprint.py", line 288, in Convert_tick_data_volume_candles
>     imb_candles = self.aggregate_volumes(imb_candles, grouped_by_uni_prices, uni_sides_in_group_p, side=1)
>   File "e:\Coding\Footprints\footprint.py", line 197, in aggregate_volumes
>     candles = self.append_to_candle(candles)
>   File "e:\Coding\Footprints\footprint.py", line 140, in append_to_candle
>     candles[self.num_row, int(i)] = features[i]
> IndexError: index 1000000 is out of bounds for axis 0 with size 1000000
> ```

I get the same thing. But if you run the same thing with your former code (the `footprint_old.py` file), you will also get an error; this one: `Segmentation fault (core dumped)`. This is something that you may need to debug. I highly encourage you to work on the new `footprint.py` code; the old code has some redundancies and holes, and it also uses `numba`, which is an additional library that `mplfinance` does not currently use and may not be in their best interest to implement.

**Comment by QuantFreedom1022** [comment]
Ok thanks ... here is my video answering your question about how i think it should look
https://www.loom.com/share/e1fd597c622f43d7a60c02d307be06b7

**Comment by andrewrgarcia** [comment]
@QuantFreedom1022 I watched your video. Sorry about this format, but jumping on a call is not convenient for me. 10 minutes can quickly turn into a longer discussion; your project as of right now is not too trivial and 10 minutes is not enough to explain all this. 

With regards to your question about the index error, it's generated because your algorithm (it occurs in your former code too) appends rows in a piece-wise manner and for some cases (when not so many rows are implicitly defined I.e. low vol size), the allocation of rows is less than the ones added in the end. I can offer a quick patch to this, but it would increase the runtime to 5x, which is very inefficient. The more prudent thing to do would be for you to brainstorm / work on how to change your algorithm so that these while loops / iterations are replaced by something simpler, like for instance use lambda functions to add the new required columns (since our codes use pandas). I would also try to consolidate the footprints.py and candle_builder.py algorithms together 

About the second thing, that's great! I would advise you to try to find how to make box plots with as less Python libraries plugins as possible or use the ones already declared by mplfinance; the mplfinance praises itself on being a lean package and this is why much of the algorithm must be optimized before incorporating it to mplfinance as a PR

**Comment by QuantFreedom1022** [comment]
Ok thanks for the suggestions ... right now I am finishing up a project and once I am done with that I'll return to this

**Pull request merged**
